/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Server;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author afons
 */
public class Server extends javax.swing.JFrame {
    
    ServiceServer worker;
    /**
     * Creates new form Server
     */
    public Server() {
        initComponents();
        this.log.setText("Servidor Fractal");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LServidorBalanciador = new javax.swing.JLabel();
        LPorta = new javax.swing.JLabel();
        startProcessing = new javax.swing.JButton();
        tXServidorBalanciadorIp = new javax.swing.JTextField();
        tXPorta = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        log = new javax.swing.JTextArea();
        stopProcessing = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        tXServidorBalanciadorPorta = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        LServidorBalanciador.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LServidorBalanciador.setText("Servidor Balanceador");

        LPorta.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LPorta.setText("Porta");

        startProcessing.setText("Start");
        startProcessing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startProcessingActionPerformed(evt);
            }
        });

        tXServidorBalanciadorIp.setText("127.0.0.1");
        tXServidorBalanciadorIp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tXServidorBalanciadorIpActionPerformed(evt);
            }
        });

        tXPorta.setText("3000");
        tXPorta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tXPortaActionPerformed(evt);
            }
        });

        log.setColumns(20);
        log.setRows(5);
        jScrollPane1.setViewportView(log);

        stopProcessing.setText("Stop");
        stopProcessing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopProcessingActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText(":");

        tXServidorBalanciadorPorta.setText("5000");
        tXServidorBalanciadorPorta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tXServidorBalanciadorPortaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LPorta, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(113, 113, 113)
                        .addComponent(tXPorta))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LServidorBalanciador)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tXServidorBalanciadorIp, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tXServidorBalanciadorPorta, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(142, 142, 142)))
                .addGap(49, 49, 49)
                .addComponent(startProcessing, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(stopProcessing, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tXServidorBalanciadorIp, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LServidorBalanciador, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(tXServidorBalanciadorPorta, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tXPorta, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LPorta, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(stopProcessing, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(startProcessing, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tXServidorBalanciadorIpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tXServidorBalanciadorIpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tXServidorBalanciadorIpActionPerformed

    private void tXPortaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tXPortaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tXPortaActionPerformed

    private void startProcessingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startProcessingActionPerformed
        if(this.worker == null || this.worker.getStop()){
            this.worker = new ServiceServer(this.log, this.tXServidorBalanciadorIp,this.tXServidorBalanciadorPorta, this.tXPorta);
            this.worker.execute();
        }
        else this.log.setText(this.log.getText() + "\n" + "Servidor já se encontra ligado");
    }//GEN-LAST:event_startProcessingActionPerformed

    private void stopProcessingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopProcessingActionPerformed
        try {
            // TODO add your handling code here:
            if(!this.worker.getStop()){
                this.worker.goodbye();
                this.worker.stop();
            }
            else this.log.setText(this.log.getText() + "\n" + "Servidor já se encontra desligado");
        } catch (Exception ex) {
            Logger.getLogger(Server.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_stopProcessingActionPerformed

    private void tXServidorBalanciadorPortaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tXServidorBalanciadorPortaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tXServidorBalanciadorPortaActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed

    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try {
            if(!this.worker.getStop()){
                this.worker.stop();
                this.worker.goodbye();
            }
        } catch (Exception ex) {}
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Server().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LPorta;
    private javax.swing.JLabel LServidorBalanciador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea log;
    private javax.swing.JButton startProcessing;
    private javax.swing.JButton stopProcessing;
    private javax.swing.JTextField tXPorta;
    private javax.swing.JTextField tXServidorBalanciadorIp;
    private javax.swing.JTextField tXServidorBalanciadorPorta;
    // End of variables declaration//GEN-END:variables
}
